SHELL := /bin/bash

# Makefile for env init and other tasks
#
# Inspiration from:
# http://docs.python-guide.org/en/latest/writing/structure/#makefile

init:
	true && \
		true && \
		echo "That's also true!"

clean:
	echo "Do something to clean up here 🤖 😊"

.PHONY: init clean
